from pathlib import Path

case = Path('cases/66-nvme14-persistent-event-log-history.md')
evidence = Path('evidence/66-nvme14-2019-persistent-event-log-grounding.md')
roadmap = Path('ROADMAP.md')
index = Path('CASE_INDEX.md')
for p in (case, evidence, roadmap, index):
    if not p.exists():
        raise SystemExit(f'missing required file: {p}')

case_marker = '## 2019 public-release / operation-phase evidence deepening'
if case_marker not in case.read_text(encoding='utf-8'):
    with case.open('a', encoding='utf-8') as f:
        f.write('''\n\n## 2019 public-release / operation-phase evidence deepening\n\nThis bounded addendum closes two small evidence gaps without changing Case 66's mechanism scope. NVM Express' first-party announcement is precisely dated **23 July 2019**; the ratified Revision 1.4 document itself is dated **10 June 2019**. Therefore `specification document date != public-release announcement date != invention / first-implementation date`.\n\nSections 5.14.1.13.1.7-10 also sharpen the event-history/effect boundary. `Format NVM Start` is recorded after parameter validation but **before modifying any NVM contents**; `Format NVM Completion` is recorded after a Format command that modified NVM contents completes and carries status/incomplete-format information. `Sanitize Start` is recorded at operation start, while `Sanitize Completion` is recorded at completion and carries sanitize progress/status information.\n\nTherefore `retained operation-start evidence != evidence that the operation completed`, and `controller-reported completion/status evidence != independent proof of lower-layer physical erasure`. Case 66 concerns retained historical evidence; Cases 44 and 47 remain responsible for command-level sanitize semantics and empirical remanence. The Start/Completion pairing shows that a retained history can preserve **phase-qualified evidence** about one maintenance action rather than an undifferentiated fact that “format happened” or “sanitize happened.”\n''')

evidence_marker = '## 2026 deepening — precise 2019 release chronology and phase-qualified maintenance evidence'
if evidence_marker not in evidence.read_text(encoding='utf-8'):
    with evidence.open('a', encoding='utf-8') as f:
        f.write('''\n\n## 2026 deepening — precise 2019 release chronology and phase-qualified maintenance evidence\n\n### P10 — first-party public-release date\n\nNVM Express, Inc., **“New NVM Express, Inc. Specifications Bolster Cloud and Enterprise Advancements,” 23 July 2019**: <https://nvmexpress.org/new-nvm-express-inc-specifications-bolster-cloud-and-enterprise-advancements/>. The dateline says NVM Express announced release of the NVMe 1.4 Base Specification. This refines the older source register, which recorded only the year. Safe chronology: Revision 1.4 document date **10 June 2019**; first-party release announcement **23 July 2019**. Neither date establishes first proposal, invention, implementation, or shipment.\n\n### P11 — Format NVM Start / Completion phase boundary\n\nRevision 1.4 §5.14.1.13.1.7 requires a Format NVM Start event after successful parameter validation and **before modifying any contents of the NVM**. §5.14.1.13.1.8 records Completion when a Format NVM command that resulted in NVM-content modification completes; the event carries status fields that can represent incomplete or unsuccessful outcomes. Safe relation: `Format Start event != Format Completion event != proof of one universal physical rewrite/erase effect`.\n\n### P12 — Sanitize Start / Completion phase boundary\n\nRevision 1.4 §5.14.1.13.1.9 records Sanitize Start at the start of a sanitize operation. §5.14.1.13.1.10 records Sanitize Completion at completion and carries Sanitize Progress, Sanitize Status, and vendor-specific completion information. Safe relations: `Sanitize Start record != Sanitize Completion record`; `controller-recorded completion/status evidence != independent lower-layer forensic-erasure proof`. This is an engineering/evidentiary boundary, not a claim that successful sanitize is ineffective. Cases 44 and 47 remain the sanitize-effect/remanence cases.\n\nThe retention-specific consequence is that PEL can preserve **which phase the controller recorded** after the live operation is gone. A surviving Start entry may outlive an interrupted operation; even a Completion entry remains controller evidence about the operation rather than the destructive mechanism itself. Still open: proposal genealogy, named-device power-loss traces between Start and Completion, and independent physical validation.\n''')

roadmap_text = roadmap.read_text(encoding='utf-8')
roadmap_line = "- [x] **NVMe PEL operation-phase evidence boundary** (Case 66 deepening): the 23-Jul-2019 NVM Express release announcement is separated from the 10-Jun-2019 specification date, and Format/Sanitize Start vs Completion records are grounded as phase-qualified history: `operation-start record != completion record != independent physical-effect proof`. Cases 44/47 remain the sanitize/remanence boundary; proposal genealogy and named-device power-loss validation remain open."
if 'NVMe PEL operation-phase evidence boundary' not in roadmap_text:
    lines = roadmap_text.splitlines()
    hits = [i for i, line in enumerate(lines) if 'NVMe PEL reporting-generation boundary' in line and '(Case 66)' in line]
    if len(hits) != 1:
        raise SystemExit(f'expected one Case 66 roadmap anchor, found {len(hits)}')
    lines.insert(hits[0] + 1, roadmap_line)
    roadmap.write_text('\n'.join(lines) + ('\n' if roadmap_text.endswith('\n') else ''), encoding='utf-8')

index_text = index.read_text(encoding='utf-8')
marker = '## Case 66 deepening — 2019 release chronology and maintenance-operation phase evidence'
if marker not in index_text:
    if '**3118 — related-repository boundary:**' not in index_text:
        raise SystemExit('finding 3118 tail anchor not found')
    index.write_text(index_text.rstrip() + '''\n\n## Case 66 deepening — 2019 release chronology and maintenance-operation phase evidence\n\nGrounding record: [`evidence/66-nvme14-2019-persistent-event-log-grounding.md`](evidence/66-nvme14-2019-persistent-event-log-grounding.md).\n\n- **3119 — specification date != public-release announcement != invention date:** Revision 1.4 is dated 10-Jun-2019; NVM Express' first-party release announcement is dated 23-Jul-2019; neither proves first proposal, implementation, shipment, or invention priority. (`H/P`, `X`)\n- **3120 — Format NVM Start evidence precedes content modification:** the Start event is required after parameter validation but before modifying NVM contents, so it cannot by itself prove the intended format effect occurred. (`H/P`, `E`)\n- **3121 — Format NVM Completion evidence != generic success:** the Completion event follows a Format command that modified NVM contents and carries fields able to represent incomplete/unsuccessful outcomes. (`H/P`, `E`)\n- **3122 — Sanitize Start record != Sanitize Completion record:** distinct event types preserve operation phase rather than one undifferentiated `sanitize happened` fact. (`H/P`, `E`)\n- **3123 — Sanitize Completion record != independent physical-erasure proof:** PEL carries controller-reported progress/status/completion evidence; Cases 44/47 remain the separate command/effect/remanence boundary. (`H/P`, `E`, `A`, `X`)\n- **3124 — retained history can preserve process phase after live execution disappears:** Start/Completion pairing gives historical evidence whose meaning depends on recorded phase, not mere event presence. (`E`)\n- **3125 — phase evidence != operation mechanism:** PEL entries describe recorded transitions; they do not themselves perform format/sanitize work. (`E`, `X`)\n- **3126 — chronology/evidence deepening != genealogy claim:** tighter 2019 chronology and phase semantics do not establish PEL proposal ancestry, first implementation, or ATA/SCSI-to-NVMe descent. (`H/P`, `X`)\n''', encoding='utf-8')
